{
	"id": "CVE-2023-26151",
	"references": [
		{
			"type": "exploit",
			"source": "NVD",
			"url": "https://gist.github.com/artfire52/1540b234350795e0ecb4d672608dbec8",
			"time_stamp": "2023-10-04T17:12:00Z"
		},
		{
			"type": "exploit",
			"source": "NVD",
			"url": "https://security.snyk.io/vuln/SNYK-PYTHON-ASYNCUA-5673709",
			"time_stamp": "2023-10-04T17:12:00Z"
		},
		{
			"type": "exploit",
			"source": "NVD",
			"url": "https://github.com/FreeOpcUa/opcua-asyncio/issues/1013",
			"time_stamp": "2023-10-04T17:12:00Z"
		}
	]
}
