{
	"id": "CVE-2022-48560",
	"references": [
		{
			"type": "exploit",
			"source": "NVD",
			"url": "https://bugs.python.org/issue39421",
			"time_stamp": "2023-08-26T02:16:00Z"
		}
	]
}
