{
  "id": "CVE-2022-40899",
  "references": [
    {
      "type": "exploit",
      "source": "NVD",
      "url": "https://github.com/python/cpython/pull/17157",
      "time_stamp": "2022-12-30T22:14:00Z"
    },
    {
      "type": "exploit",
      "source": "NVD",
      "url": "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/",
      "time_stamp": "2022-12-30T22:14:00Z"
    }
  ]
}
