{
  "id": "CVE-2022-40898",
  "references": [
    {
      "type": "exploit",
      "source": "NVD",
      "url": "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/",
      "time_stamp": "2022-12-30T22:15:00Z"
    }
  ]
}
